package main.java.de.voidtech.ytparty.handlers.user;

import org.json.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;

import main.java.de.voidtech.ytparty.annotations.Handler;
import main.java.de.voidtech.ytparty.entities.ephemeral.AuthResponse;
import main.java.de.voidtech.ytparty.entities.ephemeral.GatewayConnection;
import main.java.de.voidtech.ytparty.entities.persistent.User;
import main.java.de.voidtech.ytparty.handlers.AbstractHandler;
import main.java.de.voidtech.ytparty.service.GatewayAuthService;
import main.java.de.voidtech.ytparty.service.GatewayResponseService;
import main.java.de.voidtech.ytparty.service.UserService;

@Handler
public class ChangeAvatarHandler extends AbstractHandler {

	@Autowired
	private GatewayAuthService authService; //AuthService is used to validate Tokens and Room IDs
	
	@Autowired
	private UserService userService; //User service is needed to modify user data
	
	@Autowired
	private GatewayResponseService responder; //Responder is needed to send data back to client
	
	@Override
	public void execute(GatewayConnection session, JSONObject data) {
		String token = data.getString("token"); //Get the token
		String avatar = data.getString("avatar"); //Get the avatar choice
		
		AuthResponse tokenResponse = authService.validateToken(token); //Validate the token
		
		//Is the token valid? if not, send the message generated by the authenticator
		if (!tokenResponse.isSuccessful()) responder.sendError(session, tokenResponse.getMessage(), this.getHandlerType());
		//Otherwise, we can do exactly what we did before, but change the avatar this time instead.
		else {
			String username = tokenResponse.getActingString(); //Get the username from the auth response
			User user = userService.getUser(username); //Get the user from the DB
			user.setProfilePicture(avatar); //Set their avatar
			userService.saveUser(user); //Save the changes
			responder.sendSuccess(session, new JSONObject().put("message", "Avatar changed!"), this.getHandlerType());
			//Send a success message
		}
	}

	@Override
	public String getHandlerType() {
		return "user-changeavatar";
	}

	@Override
	public boolean requiresRateLimit() {
		return true;
	}

}
